'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBDemoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBDemoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C__MigrationHistory() As DbSet(Of C__MigrationHistory)
    Public Overridable Property Entries() As DbSet(Of Entry)
    Public Overridable Property Projects() As DbSet(Of Project)
    Public Overridable Property Tasks() As DbSet(Of Task)
    Public Overridable Property Users() As DbSet(Of User)

End Class
