'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Entry
    Public Property EntryId As Integer
    Public Property Description As String
    Public Property NbHours As Decimal
    Public Property EntryDate As Date
    Public Property User_Id As Integer
    Public Property Project_Id As Integer
    Public Property Task_Id As Integer
    Public Property CreatedDate As Nullable(Of Date)
    Public Property UpdatedDate As Nullable(Of Date)
    Public Property DeletedDate As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property User As User
    Public Overridable Property Project As Project
    Public Overridable Property Task As Task

End Class
