'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Project
    Public Property ProjectId As Integer
    Public Property Name As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property UpdatedDate As Nullable(Of Date)
    Public Property DeletedDate As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property Entries As ICollection(Of Entry) = New HashSet(Of Entry)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
